cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:3000

spring.datasource.url=jdbc:mysql://localhost:3307/amazia?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
spring.datasource.username=amazia
spring.datasource.password=amazia_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
